#!/usr/bin/bash
echo 'rm backup*.zip'
rm backup*.zip

TIMESTAMP=$(date +"%Y-%m-%d-%H-%M-%S")
ZIP_FILENAME="backup-Teduh-$TIMESTAMP.zip"

echo "zip -r \"$ZIP_FILENAME\" *"
zip -r "$ZIP_FILENAME" *

echo "cp -f \"$ZIP_FILENAME\" ~/Downloads"
cp -f "$ZIP_FILENAME" ~/Downloads
